name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app

      # - name: Install CocoaPods dependencies
      #   run: pod install


      - name: Build
        run: |
          xcodebuild clean build \
            -scheme "MyApp" \
            -workspace "MyApp.xcworkspace" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14' \
            ONLY_ACTIVE_ARCH=YES


      - name: Run tests
        run: |
          xcodebuild clean test \
            -scheme "MyApp" \
            -workspace "MyApp.xcworkspace" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14' \
            ONLY_ACTIVE_ARCH=YES


      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult


